name = "kin-sync"
main = "worker.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "kin-sync"
# Sostituisci con l'id stampato da: wrangler d1 create kin-sync
database_id = "59d6837c-51b3-417f-a9a5-82bfe5bb8bf4"
